services:
  - type: web
    name: vectal-ai
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: NODE_VERSION
        value: 18
